scraper_documentaries = ScraperDocumentaries.new
scraper_documentaries.scrape_dokumentarne
scraper_documentaries.scrape_docunet
scraper_documentaries.scrape_belgesell
scraper_documentaries.scrape_magyarvagyok
scraper_documentaries.scrape_lrt
scraper_documentaries.scrape_docverdade
scraper_documentaries.scrape_nrkskole